import React, { useState } from "react";
import PropTypes from "prop-types";
import { Link } from "react-router-dom";
import {
    ArrowRight,
    Box,
    Check,
    Code2,
    Cpu,
    Eye,
    Flame,
    Layers,
    Maximize2,
    Plus,
    RotateCw,
    Search,
    Send,
    Sliders,
    Sparkles,
    Sun,
    Zap,
} from "lucide-react";
import { Dagger3DShowcase } from "./LandingExtendedIllustrations";

const MODELS = [
    {
        id: 1,
        name: "Cyber Dagger (赛博光刃)",
        category: "Melee Weapon",
        polys: "1,240 Tris",
        codeSize: "4.2 KB",
        active: true,
    },
    {
        id: 2,
        name: "Mech Blade (机甲重刃)",
        category: "Sci-Fi Weapon",
        polys: "2,180 Tris",
        codeSize: "6.8 KB",
        active: false,
    },
    {
        id: 3,
        name: "Energy Kunai (能量苦无)",
        category: "Particle Prop",
        polys: "980 Tris",
        codeSize: "3.4 KB",
        active: false,
    },
    {
        id: 4,
        name: "Quantum Core (量子核心)",
        category: "Interactive Asset",
        polys: "3,450 Tris",
        codeSize: "8.1 KB",
        active: false,
    },
];

const CODE_SNIPPETS = {
    1: `// Procedural Cyber Dagger Generated by DinQor img2threejs (gpt-5.6-terra)
import * as THREE from 'three';

export function createCyberDagger() {
  const root = new THREE.Group();
  
  // 1. Procedural Blade Geometry (Non-binary, pure math)
  const bladeShape = new THREE.Shape();
  bladeShape.moveTo(0, 0);
  bladeShape.lineTo(0.4, 2.8);
  bladeShape.lineTo(0.0, 3.4);
  bladeShape.lineTo(-0.4, 2.8);
  
  const extrudeSettings = { depth: 0.1, bevelEnabled: true, bevelSegments: 3 };
  const bladeGeo = new THREE.ExtrudeGeometry(bladeShape, extrudeSettings);
  const bladeMat = new THREE.MeshStandardMaterial({
    color: 0x6366f1,
    metalness: 0.95,
    roughness: 0.12,
    emissive: 0x4338ca,
    emissiveIntensity: 0.6
  });
  const bladeMesh = new THREE.Mesh(bladeGeo, bladeMat);
  root.add(bladeMesh);

  // 2. Attach Skeleton Sockets
  root.userData.sockets = { rightHand: new THREE.Vector3(0, -0.5, 0) };
  return root;
}`,
    2: `// Procedural Mech Blade Generated by DinQor img2threejs (gpt-5.6-terra)
import * as THREE from 'three';

export function createMechBlade() {
  const group = new THREE.Group();
  const spineGeo = new THREE.BoxGeometry(0.3, 4.2, 0.15);
  const spineMat = new THREE.MeshPhysicalMaterial({
    metalness: 0.98,
    roughness: 0.08,
    clearcoat: 1.0
  });
  group.add(new THREE.Mesh(spineGeo, spineMat));
  return group;
}`,
    3: `// Procedural Energy Kunai Generated by DinQor img2threejs (gpt-5.6-terra)
import * as THREE from 'three';

export function createEnergyKunai() {
  const group = new THREE.Group();
  const ringGeo = new THREE.TorusGeometry(0.3, 0.06, 16, 32);
  const ringMat = new THREE.MeshStandardMaterial({ color: 0x10b981, roughness: 0.2 });
  group.add(new THREE.Mesh(ringGeo, ringMat));
  return group;
}`,
    4: `// Procedural Quantum Core Generated by DinQor img2threejs (gpt-5.6-terra)
import * as THREE from 'three';

export function createQuantumCore() {
  const group = new THREE.Group();
  const coreGeo = new THREE.IcosahedronGeometry(1.2, 2);
  const coreMat = new THREE.MeshStandardMaterial({ wireframe: true, color: 0x8b5cf6 });
  group.add(new THREE.Mesh(coreGeo, coreMat));
  return group;
}`,
};

const LandingImg2ThreejsSection = ({ t }) => {
    const [selectedModelId, setSelectedModelId] = useState(1);
    const [activeTab, setActiveTab] = useState("preview"); // "preview" | "code" | "params"
    const [wireframe, setWireframe] = useState(false);
    const [metalness, setMetalness] = useState(95);
    const [roughness, setRoughness] = useState(12);

    const currentModel = MODELS.find((m) => m.id === selectedModelId) || MODELS[0];

    return (
        <section className="relative mx-auto mt-28 w-full max-w-7xl px-3 sm:px-6 lg:px-8">
            {/* Ambient Lighting */}
            <div
                aria-hidden="true"
                className="pointer-events-none absolute -left-20 top-1/4 h-96 w-96 rounded-full bg-purple-400/15 blur-3xl"
            />
            <div
                aria-hidden="true"
                className="pointer-events-none absolute -right-20 top-1/2 h-96 w-96 rounded-full bg-violet-400/15 blur-3xl"
            />

            {/* Section Header */}
            <div className="text-center">
                <div className="inline-flex items-center gap-2 rounded-full border border-purple-200/80 bg-purple-50/80 px-4 py-1.5 text-xs font-semibold text-purple-700 shadow-xs backdrop-blur-md">
                    <Code2 className="h-3.5 w-3.5 text-purple-600" />
                    <span>{t("landing.img2threejs.badge", "纯代码 3D 资产 · 0 二进制体积 · 毫秒级即时生成")}</span>
                </div>
                <h2 className="mt-4 text-2xl font-black tracking-tight text-[#111426] sm:text-4xl">
                    {t("landing.img2threejs.title", "img2threejs —— 纯代码程序化 3D 资产工坊")}
                </h2>
                <p className="mx-auto mt-3 max-w-3xl text-xs sm:text-sm leading-relaxed text-[#606782]">
                    {t(
                        "landing.img2threejs.subtitle",
                        "无需笨重的 GLTF/FBX 二进制文件。单张图片或提示词，即可直接生成包含材质着色器、骨骼插槽与动画的纯 Three.js JavaScript 源代码。",
                    )}
                </p>
            </div>

            {/* Realistic 3D Studio Workbench Frame */}
            <div className="relative mx-auto mt-10 w-full max-w-5xl">
                {/* Outer Glass Window Frame */}
                <div className="overflow-hidden rounded-3xl border border-[#e2e8f0] bg-white shadow-[0_24px_70px_-15px_rgba(168,85,247,0.14)]">
                    {/* Top Window Bar */}
                    <div className="flex h-11 items-center justify-between border-b border-[#f0f2f8] bg-[#fafbfe] px-4">
                        <div className="flex items-center gap-2">
                            <span className="h-3 w-3 rounded-full bg-[#ff5f56]" />
                            <span className="h-3 w-3 rounded-full bg-[#ffbd2e]" />
                            <span className="h-3 w-3 rounded-full bg-[#27c93f]" />
                            <div className="ml-3 flex items-center gap-2 border-l border-[#e2e8f0] pl-3">
                                <span className="h-2 w-2 rounded-full bg-emerald-500 animate-pulse" />
                                <span className="text-xs font-bold text-[#111426]">
                                    img2threejs 3D 资产工坊
                                </span>
                                <span className="hidden sm:inline-block rounded-full bg-purple-50 px-2 py-0.5 text-[10px] font-semibold text-purple-700">
                                    gpt-5.6-terra · WebGL 纯代码资产编译器
                                </span>
                            </div>
                        </div>

                        <div className="flex items-center gap-2">
                            <Link
                                to="/workspace/img2three"
                                className="flex items-center gap-1 rounded-lg px-2.5 py-1 text-xs font-semibold text-purple-600 hover:bg-purple-50 transition-colors"
                            >
                                <span>进入 3D 资产工坊</span>
                                <ArrowRight className="h-3.5 w-3.5" />
                            </Link>
                        </div>
                    </div>

                    {/* Window Layout: Left 3D Assets Sidebar Slice + Right 3D Studio Area */}
                    <div className="flex min-h-[520px] flex-col md:flex-row">
                        {/* Left Assets Sidebar Slice */}
                        <div className="flex w-full md:w-64 shrink-0 flex-col justify-between border-r border-[#f0f2f8] bg-[#fafafc] p-3">
                            <div>
                                {/* Generate New 3D Asset Button */}
                                <button
                                    type="button"
                                    className="flex w-full items-center justify-center gap-2 rounded-2xl bg-purple-600 py-2.5 text-xs font-semibold text-white shadow-xs transition-transform active:scale-95 hover:bg-purple-700"
                                >
                                    <Plus className="h-4 w-4" />
                                    <span>生成新 3D 资产</span>
                                </button>

                                {/* Search Input Mock */}
                                <div className="mt-3 flex items-center gap-2 rounded-xl border border-[#e2e8f0] bg-white px-2.5 py-1.5 text-xs text-[#8e94aa]">
                                    <Search className="h-3.5 w-3.5" />
                                    <span className="text-[11px]">搜索 3D 资产库...</span>
                                </div>

                                {/* Models List */}
                                <div className="mt-3 space-y-1">
                                    <div className="px-1 text-[10px] font-bold text-[#9ea3b9] uppercase tracking-wider">
                                        已编译的程序化 3D 资产
                                    </div>
                                    {MODELS.map((model) => {
                                        const isSelected = selectedModelId === model.id;
                                        return (
                                            <button
                                                key={model.id}
                                                type="button"
                                                onClick={() => setSelectedModelId(model.id)}
                                                className={`group flex w-full cursor-pointer items-center justify-between rounded-xl px-2.5 py-2 text-left transition-colors ${
                                                    isSelected
                                                        ? "bg-purple-50 text-purple-950 font-semibold"
                                                        : "text-[#242741] hover:bg-[#f7f6fc]"
                                                }`}
                                            >
                                                <div className="flex min-w-0 items-center gap-2">
                                                    <Box
                                                        className={`h-3.5 w-3.5 shrink-0 ${
                                                            isSelected ? "text-purple-600" : "text-[#9ea3b9]"
                                                        }`}
                                                    />
                                                    <div className="min-w-0">
                                                        <div className="truncate text-xs">{model.name}</div>
                                                        <div className="text-[10px] text-[#9ea3b9]">{model.polys} · {model.codeSize}</div>
                                                    </div>
                                                </div>
                                                <span className="shrink-0 font-mono text-[9px] font-bold text-purple-600">
                                                    JS
                                                </span>
                                            </button>
                                        );
                                    })}
                                </div>
                            </div>

                            {/* Sidebar Footer Stats */}
                            <div className="rounded-xl border border-[#edf0f8] bg-white p-2.5 text-center">
                                <div className="text-[10px] text-[#8e94aa]">运行时体积消耗</div>
                                <div className="mt-0.5 text-xs font-bold text-emerald-600">0 MB 二进制 / 100% 纯代码</div>
                            </div>
                        </div>

                        {/* Right Main Studio Viewport Slice */}
                        <div className="flex min-w-0 flex-1 flex-col justify-between bg-white">
                            {/* Studio Header with View Mode Tabs */}
                            <div className="flex items-center justify-between border-b border-[#f0f2f8] px-4 py-2.5">
                                <div className="min-w-0">
                                    <h3 className="truncate text-xs sm:text-sm font-bold text-[#111426]">
                                        {currentModel.name}
                                    </h3>
                                    <div className="text-[10px] text-[#8e94aa]">
                                        资产分类：{currentModel.category} · 拓扑面数：{currentModel.polys} · 源码大小：{currentModel.codeSize}
                                    </div>
                                </div>
                                <div className="flex items-center gap-1.5">
                                    <button
                                        type="button"
                                        onClick={() => setActiveTab("preview")}
                                        className={`flex items-center gap-1 rounded-lg px-2.5 py-1 text-xs font-semibold transition-colors ${
                                            activeTab === "preview"
                                                ? "bg-purple-600 text-white shadow-xs"
                                                : "bg-[#f1f5f9] text-[#64748b] hover:bg-[#e2e8f0]"
                                        }`}
                                    >
                                        <Eye className="h-3.5 w-3.5" />
                                        <span>3D 视口</span>
                                    </button>
                                    <button
                                        type="button"
                                        onClick={() => setActiveTab("code")}
                                        className={`flex items-center gap-1 rounded-lg px-2.5 py-1 text-xs font-semibold transition-colors ${
                                            activeTab === "code"
                                                ? "bg-purple-600 text-white shadow-xs"
                                                : "bg-[#f1f5f9] text-[#64748b] hover:bg-[#e2e8f0]"
                                        }`}
                                    >
                                        <Code2 className="h-3.5 w-3.5" />
                                        <span>源码审查</span>
                                    </button>
                                    <button
                                        type="button"
                                        onClick={() => setActiveTab("params")}
                                        className={`flex items-center gap-1 rounded-lg px-2.5 py-1 text-xs font-semibold transition-colors ${
                                            activeTab === "params"
                                                ? "bg-purple-600 text-white shadow-xs"
                                                : "bg-[#f1f5f9] text-[#64748b] hover:bg-[#e2e8f0]"
                                        }`}
                                    >
                                        <Sliders className="h-3.5 w-3.5" />
                                        <span>材质调参</span>
                                    </button>
                                </div>
                            </div>

                            {/* Main Studio Body: Tab Dependent */}
                            <div className="flex-1 overflow-y-auto p-4 sm:p-6 space-y-4">
                                {activeTab === "preview" && (
                                    /* 3D Viewport with 360 Turntable & Wireframe Switch */
                                    <div className="relative flex flex-col items-center justify-center rounded-2xl border border-border bg-[#0d111d] p-4 text-white shadow-xs">
                                        <div className="absolute left-3 top-3 flex items-center gap-2 text-micro font-mono text-purple-300">
                                            <span className="h-2 w-2 rounded-full bg-emerald-400 animate-ping" />
                                            <span>WebGL 60 FPS · 360° 交互式转盘</span>
                                        </div>
                                        <div className="absolute right-3 top-3 flex items-center gap-2">
                                            <button
                                                type="button"
                                                onClick={() => setWireframe(!wireframe)}
                                                className={`rounded-lg border px-2 py-1 text-micro font-bold transition-all ${
                                                    wireframe
                                                        ? "border-purple-400 bg-purple-600 text-white"
                                                        : "border-white/20 bg-white/10 text-slate-300 hover:bg-white/20"
                                                }`}
                                            >
                                                {wireframe ? "Wireframe 开" : "Wireframe 关"}
                                            </button>
                                        </div>

                                        <div className="my-6 w-full flex justify-center">
                                            <Dagger3DShowcase className="h-44 w-full" />
                                        </div>

                                        <div className="w-full flex items-center justify-between border-t border-white/10 pt-2.5 text-micro text-slate-400">
                                            <span>右键平移 · 滚轮缩放 · 骨骼插槽右手机位就绪</span>
                                            <span className="font-mono text-purple-300">GPU 显存占用: 0.12 MB</span>
                                        </div>
                                    </div>
                                )}

                                {activeTab === "code" && (
                                    /* Live Three.js JavaScript Code Inspector */
                                    <div className="overflow-hidden rounded-2xl border border-[#1e293b] bg-[#0d111d] p-4 text-white shadow-xs font-mono text-[11px]">
                                        <div className="flex items-center justify-between border-b border-white/10 pb-2 text-micro text-slate-400">
                                            <span className="text-purple-300">three_generated_asset.js (ES Module)</span>
                                            <span className="text-emerald-400">Pure Code / No Binary</span>
                                        </div>
                                        <pre className="mt-3 max-h-56 overflow-y-auto text-purple-200 leading-relaxed scrollbar-thin">
                                            {CODE_SNIPPETS[selectedModelId]}
                                        </pre>
                                    </div>
                                )}

                                {activeTab === "params" && (
                                    /* Live PBR Material Parameters Tuner */
                                    <div className="rounded-2xl border border-border bg-[#fcfdff] p-5 shadow-xs">
                                        <div className="flex items-center justify-between border-b border-border pb-3">
                                            <span className="text-xs font-bold text-ink">
                                                PBR 物理材质着色器实时调参
                                            </span>
                                            <span className="text-micro font-mono text-purple-600 font-bold">
                                                MeshPhysicalMaterial
                                            </span>
                                        </div>

                                        <div className="mt-4 space-y-4">
                                            <div>
                                                <div className="flex justify-between text-xs font-semibold text-ink-secondary">
                                                    <span>金属度 (Metalness)</span>
                                                    <span className="font-mono text-purple-600">{(metalness / 100).toFixed(2)}</span>
                                                </div>
                                                <input
                                                    type="range"
                                                    min="0"
                                                    max="100"
                                                    value={metalness}
                                                    onChange={(e) => setMetalness(Number(e.target.value))}
                                                    className="mt-2 w-full accent-purple-600"
                                                />
                                            </div>

                                            <div>
                                                <div className="flex justify-between text-xs font-semibold text-ink-secondary">
                                                    <span>粗糙度 (Roughness)</span>
                                                    <span className="font-mono text-purple-600">{(roughness / 100).toFixed(2)}</span>
                                                </div>
                                                <input
                                                    type="range"
                                                    min="0"
                                                    max="100"
                                                    value={roughness}
                                                    onChange={(e) => setRoughness(Number(e.target.value))}
                                                    className="mt-2 w-full accent-purple-600"
                                                />
                                            </div>
                                        </div>
                                    </div>
                                )}
                            </div>

                            {/* Bottom Composer Bar */}
                            <div className="border-t border-[#f0f2f8] bg-white p-3 sm:p-4">
                                <div className="relative rounded-[1.75rem] border border-[#e5e7f2] bg-white p-1.5 shadow-[0_4px_20px_rgba(168,85,247,0.04)]">
                                    <div className="flex items-center gap-2">
                                        <button
                                            type="button"
                                            className="grid h-8 w-8 place-items-center rounded-full text-[#8e94aa] hover:bg-purple-50 hover:text-purple-700 transition-colors"
                                            title="材质贴图或提示词"
                                        >
                                            <Box className="h-4 w-4" />
                                        </button>
                                        <input
                                            type="text"
                                            readOnly
                                            value="上传一张 2D 原画或描述“带有等离子光晕的双刃光剑”，即刻生成纯 JS 源码..."
                                            className="flex-1 bg-transparent px-1 text-xs sm:text-sm text-[#8e94aa] outline-none cursor-default"
                                        />
                                        <Link
                                            to="/workspace/img2three"
                                            className="grid h-8 w-8 place-items-center rounded-full bg-purple-600 text-white shadow-xs transition-transform hover:scale-105"
                                        >
                                            <Send className="h-3.5 w-3.5" />
                                        </Link>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            {/* Bottom 3 Capability Pillars */}
            <div className="mt-8 grid grid-cols-1 gap-4 sm:grid-cols-3">
                <div className="rounded-2xl border border-[#ebeef7] bg-white p-4 shadow-2xs">
                    <div className="flex items-center gap-2 font-bold text-xs text-[#111426]">
                        <Code2 className="h-4 w-4 text-purple-600" />
                        <span>0 二进制资产革命</span>
                    </div>
                    <p className="mt-1.5 text-[11px] leading-relaxed text-[#64748b]">
                        纯代码程序化构建，数十 KB 代码替代数十 MB 模型文件，网页秒开零网络延迟。
                    </p>
                </div>
                <div className="rounded-2xl border border-[#ebeef7] bg-white p-4 shadow-2xs">
                    <div className="flex items-center gap-2 font-bold text-xs text-[#111426]">
                        <Layers className="h-4 w-4 text-indigo-600" />
                        <span>自动装配骨骼与插槽</span>
                    </div>
                    <p className="mt-1.5 text-[11px] leading-relaxed text-[#64748b]">
                        自动生成挂载点 (Weapon Socket) 与碰撞体 (Collider)，直接适配游戏角色骨骼。
                    </p>
                </div>
                <div className="rounded-2xl border border-[#ebeef7] bg-white p-4 shadow-2xs">
                    <div className="flex items-center gap-2 font-bold text-xs text-[#111426]">
                        <Sliders className="h-4 w-4 text-purple-600" />
                        <span>PBR 材质与着色器微调</span>
                    </div>
                    <p className="mt-1.5 text-[11px] leading-relaxed text-[#64748b]">
                        支持实时微调金属度、粗糙度、Clearcoat 漆面层与自发光着色器辉光。
                    </p>
                </div>
            </div>
        </section>
    );
};

LandingImg2ThreejsSection.propTypes = {
    t: PropTypes.func.isRequired,
};

export default LandingImg2ThreejsSection;
